version: 1

formatters:
  simple:
    format: "%(asctime)s %(name)s: %(message)s"
  extended:
    format: "%(asctime)s %(name)s %(levelname)s: %(message)s"
  colorlog:
    '()': 'colorlog.ColoredFormatter'
    format: '[%(cyan)s%(asctime)s%(reset)s][%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s] - %(message)s'
    log_colors:
      DEBUG: purple
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: red

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: colorlog

#file_handler:
#    class: logging.FileHandler
#    level: INFO
#    filename: test.log
#    formatter: extended
#    propagate: false

loggers:
  debug:
    level: DEBUG
    handlers: [console]
    formatter: extended
  info:
    level: INFO
    handlers: [console]
    formatter: simple
  err:
    level: ERROR
    handlers: [console]
    formatter: colorlog
#  test:
#    handlers: [file_handler]
#root:
#  handlers: [file_handler]

disable_existing_loggers: false