version: 1

formatters:
  simple:
    format: "%(asctime)s %(name)s: %(message)s"
  extended:
    format: "%(asctime)s %(name)s %(levelname)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple

#file_handler:
#    class: logging.FileHandler
#    level: INFO
#    filename: test.log
#    formatter: extended
#    propagate: false

loggers:
  debug:
    level: DEBUG
    handlers: [console]
    formatter: extended
  info:
    level: INFO
    handlers: [console]
    formatter: simple
  err:
    level: ERROR
    handlers: [console]
#  test:
#    handlers: [file_handler]
#root:
#  handlers: [file_handler]